// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertFadeoutController from "./alert_fadeout_controller"
application.register("alert-fadeout", AlertFadeoutController)

import EditMatchupsController from "./edit_matchups_controller"
application.register("edit-matchups", EditMatchupsController)

import GeneratePairingsController from "./generate_pairings_controller"
application.register("generate-pairings", GeneratePairingsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MatchupsController from "./matchups_controller"
application.register("matchups", MatchupsController)

import StartTournamentController from "./start_tournament_controller"
application.register("start-tournament", StartTournamentController)
